# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz
    - name: Run python
      run: |
        python scripts/create_README.py
        python scripts/create_LEVEL.py
    - name: Config Github
      run: |
        git add .
        git diff
        git config --local user.email "westreed@naver.com"
        git config --local user.name "JangSeHun"
        git commit -m "update README.md"
        git push
